name: macOS Apple Silicon Build

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v4.2.0

      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v4.3.1
        with:
          dotnet-version: '9.x' # Latest .NET version
    
      - name: Check architecture
        run: |
          echo "Machine architecture: $(uname -m)"
          echo "System information: $(uname -a)"
      
      - name: Install .NET MAUI workloads
        run: |
          dotnet workload install maui maui-maccatalyst maui-ios
          dotnet workload restore
    
      - name: Restore dependencies with runtime identifiers
        run: dotnet restore -r osx-arm64 -r maccatalyst-arm64
    
      - name: Build
        run: dotnet build --configuration Release --no-restore /p:RuntimeIdentifier=maccatalyst-arm64
      
      - name: Test
        run: dotnet test --configuration Release --no-build --verbosity normal
      
      - name: Publish for Apple Silicon
        run: dotnet publish -c Release -r maccatalyst-arm64 --self-contained true -o ./publish
      
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: macos-arm64-build
          path: ./publish
          if-no-files-found: error
