name: macOS Apple Silicon Build

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0.x'
    
    - name: Check architecture
      run: |
        echo "Machine architecture: $(uname -m)"
        echo "System information: $(uname -a)"
    
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build --configuration Release --no-restore
    
    - name: Test
      run: dotnet test --configuration Release --no-build --verbosity normal
    
    - name: Publish for Apple Silicon
      run: dotnet publish -c Release -r osx-arm64 --self-contained true -o ./publish
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: macos-arm64-build
        path: ./publish
